name: 🚀 Publish to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔄 Bump Version (Patch Update)
        run: |
          if git log -1 --pretty=%B | grep -iq 'major'; then
            npm version major --no-git-tag-version
          elif git log -1 --pretty=%B | grep -iq 'minor'; then
            npm version minor --no-git-tag-version
          else
            npm version patch --no-git-tag-version
          fi
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json
          git commit -m "🔖 Bump version [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Build Package
        run: npm run build
      
      - name: 🚀 Publish to npm
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

